global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: yallmp
    metrics_path: /metrics
    static_configs:
      - targets: ["yallmp:5000"]

  - job_name: llogr
    metrics_path: /metrics
    static_configs:
      - targets: ["llogr:8000"]

  - job_name: checkr
    metrics_path: /metrics
    static_configs:
      - targets: ["checkr:5000"]

  - job_name: clickstream
    metrics_path: /metrics
    static_configs:
      - targets: ["clickstream:9999"]
